package scorekeeper;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.Timer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScoreBoard.java
 *
 * Created on Jan 31, 2011, 8:53:23 PM
 */

/**
 *
 * @author jimmynewland
 */
public class ScoreBoard extends javax.swing.JFrame {

    private ArrayList<JToggleButton> buttonList;
    private int bonusTotal;
    private Timer timer;
    private int time = 60;

    /** Creates new form ScoreBoard */
    public ScoreBoard() {
        initComponents();
        bonusTotal = 0;
        sweepLabel.setVisible(false);
        buttonList = new ArrayList<JToggleButton>();
        buttonList.add(q1);
        buttonList.add(q2);
        buttonList.add(q3);
        buttonList.add(q4);
        buttonList.add(q5);
        buttonList.add(q6);
        buttonList.add(q7);
        buttonList.add(q8);
        buttonList.add(q9);
        buttonList.add(q10);
        timer = new Timer(1000, new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                if(time>=0){
                    timerLabel.setText(""+time);
                    time--;
                }
                else{
                    timerLabel.setText("Done!");
                }
            }
        }
                );
        timer.setInitialDelay(1);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        Team1Panel = new javax.swing.JPanel();
        Team1Label = new javax.swing.JLabel();
        Team1Score = new javax.swing.JLabel();
        Team1PointsPanel = new javax.swing.JPanel();
        Team1Add5 = new javax.swing.JButton();
        Team1Add10 = new javax.swing.JButton();
        Team1Add15 = new javax.swing.JButton();
        Team1Neg5 = new javax.swing.JButton();
        Team1Add20 = new javax.swing.JButton();
        Team2Panel = new javax.swing.JPanel();
        Team2Label = new javax.swing.JLabel();
        Team2Score = new javax.swing.JLabel();
        Team2PointsPanel = new javax.swing.JPanel();
        Team2Add5 = new javax.swing.JButton();
        Team2Add10 = new javax.swing.JButton();
        Team2Add15 = new javax.swing.JButton();
        Team2Neg5 = new javax.swing.JButton();
        Team2Add20 = new javax.swing.JButton();
        SixtySecondPanel = new javax.swing.JPanel();
        q1 = new javax.swing.JToggleButton();
        q2 = new javax.swing.JToggleButton();
        q3 = new javax.swing.JToggleButton();
        q4 = new javax.swing.JToggleButton();
        q5 = new javax.swing.JToggleButton();
        q6 = new javax.swing.JToggleButton();
        q7 = new javax.swing.JToggleButton();
        q8 = new javax.swing.JToggleButton();
        q9 = new javax.swing.JToggleButton();
        q10 = new javax.swing.JToggleButton();
        team1_60 = new javax.swing.JRadioButton();
        team2_60 = new javax.swing.JRadioButton();
        sweepLabel = new javax.swing.JLabel();
        SixtySecondPoints = new javax.swing.JButton();
        sixtySecPtsLabel = new javax.swing.JLabel();
        timerButton = new javax.swing.JButton();
        timerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 600));

        Team1Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Team1Panel.setPreferredSize(new java.awt.Dimension(400, 450));

        Team1Label.setFont(new java.awt.Font("Lucida Grande", 1, 48));
        Team1Label.setText("Team 1");
        Team1Label.setToolTipText("Double-click to edit"); // NOI18N
        Team1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Team1LabelMouseClicked(evt);
            }
        });

        Team1Score.setFont(new java.awt.Font("Lucida Grande", 1, 72));
        Team1Score.setText("0");
        Team1Score.setToolTipText("Double-click to edit"); // NOI18N
        Team1Score.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Team1ScoreMouseClicked(evt);
            }
        });

        Team1PointsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Team1Add5.setText("+5");
        Team1Add5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team1Add5ActionPerformed(evt);
            }
        });

        Team1Add10.setText("+10");
        Team1Add10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team1Add10ActionPerformed(evt);
            }
        });

        Team1Add15.setText("+15");
        Team1Add15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team1Add15ActionPerformed(evt);
            }
        });

        Team1Neg5.setText("-5");
        Team1Neg5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team1Neg5ActionPerformed(evt);
            }
        });

        Team1Add20.setText("+20");
        Team1Add20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team1Add20ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout Team1PointsPanelLayout = new org.jdesktop.layout.GroupLayout(Team1PointsPanel);
        Team1PointsPanel.setLayout(Team1PointsPanelLayout);
        Team1PointsPanelLayout.setHorizontalGroup(
            Team1PointsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Team1PointsPanelLayout.createSequentialGroup()
                .add(Team1PointsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Team1PointsPanelLayout.createSequentialGroup()
                        .add(Team1Add5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Team1Add10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Team1Add15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(6, 6, 6)
                        .add(Team1Add20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(Team1Neg5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Team1PointsPanelLayout.setVerticalGroup(
            Team1PointsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Team1PointsPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(Team1PointsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Team1Add5)
                    .add(Team1Add10)
                    .add(Team1Add15)
                    .add(Team1Add20))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Team1Neg5))
        );

        org.jdesktop.layout.GroupLayout Team1PanelLayout = new org.jdesktop.layout.GroupLayout(Team1Panel);
        Team1Panel.setLayout(Team1PanelLayout);
        Team1PanelLayout.setHorizontalGroup(
            Team1PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Team1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(Team1PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Team1PointsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Team1Score)
                    .add(Team1Label))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        Team1PanelLayout.setVerticalGroup(
            Team1PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Team1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(Team1Label)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Team1Score)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Team1PointsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(274, 274, 274))
        );

        Team2Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Team2Panel.setPreferredSize(new java.awt.Dimension(400, 450));

        Team2Label.setFont(new java.awt.Font("Lucida Grande", 1, 48));
        Team2Label.setText("Team 2");
        Team2Label.setToolTipText("Double-click to edit"); // NOI18N
        Team2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Team2LabelMouseClicked(evt);
            }
        });

        Team2Score.setFont(new java.awt.Font("Lucida Grande", 1, 72));
        Team2Score.setText("0");
        Team2Score.setToolTipText("Double-click to edit"); // NOI18N
        Team2Score.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Team2ScoreMouseClicked(evt);
            }
        });

        Team2PointsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Team2Add5.setText("+5");
        Team2Add5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team2Add5ActionPerformed(evt);
            }
        });

        Team2Add10.setText("+10");
        Team2Add10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team2Add10ActionPerformed(evt);
            }
        });

        Team2Add15.setText("+15");
        Team2Add15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team2Add15ActionPerformed(evt);
            }
        });

        Team2Neg5.setText("-5");
        Team2Neg5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team2Neg5ActionPerformed(evt);
            }
        });

        Team2Add20.setText("+20");
        Team2Add20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Team2Add20ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout Team2PointsPanelLayout = new org.jdesktop.layout.GroupLayout(Team2PointsPanel);
        Team2PointsPanel.setLayout(Team2PointsPanelLayout);
        Team2PointsPanelLayout.setHorizontalGroup(
            Team2PointsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Team2PointsPanelLayout.createSequentialGroup()
                .add(Team2PointsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Team2PointsPanelLayout.createSequentialGroup()
                        .add(Team2Add5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Team2Add10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(Team2Add15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(6, 6, 6)
                        .add(Team2Add20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(Team2Neg5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Team2PointsPanelLayout.setVerticalGroup(
            Team2PointsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Team2PointsPanelLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(Team2PointsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(Team2Add5)
                    .add(Team2Add10)
                    .add(Team2Add15)
                    .add(Team2Add20))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Team2Neg5))
        );

        org.jdesktop.layout.GroupLayout Team2PanelLayout = new org.jdesktop.layout.GroupLayout(Team2Panel);
        Team2Panel.setLayout(Team2PanelLayout);
        Team2PanelLayout.setHorizontalGroup(
            Team2PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Team2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(Team2PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(Team2PointsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(Team2Label)
                    .add(Team2Score))
                .addContainerGap())
        );
        Team2PanelLayout.setVerticalGroup(
            Team2PanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(Team2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(Team2Label)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Team2Score)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Team2PointsPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        SixtySecondPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("60 Second Round"));
        SixtySecondPanel.setPreferredSize(new java.awt.Dimension(250, 500));

        q1.setText("1");
        q1.setEnabled(false);
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });

        q2.setText("2");
        q2.setEnabled(false);
        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });

        q3.setText("3");
        q3.setEnabled(false);
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });

        q4.setText("4");
        q4.setEnabled(false);
        q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4ActionPerformed(evt);
            }
        });

        q5.setText("5");
        q5.setEnabled(false);
        q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5ActionPerformed(evt);
            }
        });

        q6.setText("6");
        q6.setEnabled(false);
        q6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6ActionPerformed(evt);
            }
        });

        q7.setText("7");
        q7.setEnabled(false);
        q7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q7ActionPerformed(evt);
            }
        });

        q8.setText("8");
        q8.setEnabled(false);
        q8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q8ActionPerformed(evt);
            }
        });

        q9.setText("9");
        q9.setEnabled(false);
        q9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q9ActionPerformed(evt);
            }
        });

        q10.setText("10");
        q10.setEnabled(false);
        q10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q10ActionPerformed(evt);
            }
        });

        buttonGroup.add(team1_60);
        team1_60.setText("Team 1");
        team1_60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team1_60ActionPerformed(evt);
            }
        });

        buttonGroup.add(team2_60);
        team2_60.setText("Team 2");
        team2_60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team2_60ActionPerformed(evt);
            }
        });

        sweepLabel.setFont(new java.awt.Font("Lucida Grande", 1, 12));
        sweepLabel.setText("Sweep! +20");
        sweepLabel.setOpaque(true);

        SixtySecondPoints.setText("Add Points");
        SixtySecondPoints.setToolTipText("Add 60 second round total to selected team point total."); // NOI18N
        SixtySecondPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixtySecondPointsActionPerformed(evt);
            }
        });

        sixtySecPtsLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        sixtySecPtsLabel.setText("0");

        timerButton.setText("Start");
        timerButton.setEnabled(false);
        timerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timerButtonActionPerformed(evt);
            }
        });

        timerLabel.setFont(new java.awt.Font("Lucida Grande", 1, 24));
        timerLabel.setText("60");

        org.jdesktop.layout.GroupLayout SixtySecondPanelLayout = new org.jdesktop.layout.GroupLayout(SixtySecondPanel);
        SixtySecondPanel.setLayout(SixtySecondPanelLayout);
        SixtySecondPanelLayout.setHorizontalGroup(
            SixtySecondPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SixtySecondPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(SixtySecondPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(SixtySecondPanelLayout.createSequentialGroup()
                        .add(SixtySecondPoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sixtySecPtsLabel))
                    .add(team1_60)
                    .add(team2_60)
                    .add(SixtySecondPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                        .add(q10)
                        .add(q9)
                        .add(q8)
                        .add(q6)
                        .add(q7)
                        .add(q5)
                        .add(q4)
                        .add(q3)
                        .add(q2)
                        .add(q1)
                        .add(sweepLabel))
                    .add(SixtySecondPanelLayout.createSequentialGroup()
                        .add(timerButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(timerLabel)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        SixtySecondPanelLayout.setVerticalGroup(
            SixtySecondPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(SixtySecondPanelLayout.createSequentialGroup()
                .add(team1_60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(team2_60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(7, 7, 7)
                .add(SixtySecondPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(timerButton)
                    .add(timerLabel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(SixtySecondPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(SixtySecondPanelLayout.createSequentialGroup()
                        .add(q1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(q2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(q3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(q4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(q5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(q6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(q7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(q8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(q9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(q10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sweepLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(SixtySecondPoints, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(sixtySecPtsLabel))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(Team1Panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .add(14, 14, 14)
                .add(SixtySecondPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(Team2Panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, SixtySecondPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, Team2Panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, Team1Panel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Team1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Team1LabelMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() >= 2){
            String t = JOptionPane.showInputDialog("New Name",Team1Label.getText());
            if (!t.equals("")){
                Team1Label.setText(t);
                team1_60.setText(t);
            }
        }

    }//GEN-LAST:event_Team1LabelMouseClicked

    private void q10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q10ActionPerformed
        // TODO add your handling code here:
        togglePressed(q10);
    }//GEN-LAST:event_q10ActionPerformed

    private void q9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q9ActionPerformed
        // TODO add your handling code here:
        togglePressed(q9);
    }//GEN-LAST:event_q9ActionPerformed

    private void Team1ScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Team1ScoreMouseClicked
        // TODO add your handling code here:
        String t = JOptionPane.showInputDialog("New Score",Team1Score.getText());
        try{
            Integer.parseInt(t);
        }
        catch(NumberFormatException e){
            t = Team1Score.getText();
        }
        finally {
            Team1Score.setText(t);
        }
    }//GEN-LAST:event_Team1ScoreMouseClicked

    private void Team2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Team2LabelMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() >= 2){
            String t = JOptionPane.showInputDialog("New Name",Team2Label.getText());
            if(!t.equals("")){
                Team2Label.setText(t);
                team2_60.setText(t);
            }
        }
    }//GEN-LAST:event_Team2LabelMouseClicked

    private void Team2ScoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Team2ScoreMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() >= 2){
            String t = JOptionPane.showInputDialog("New Score",Team2Score.getText());
            try{
                Integer.parseInt(t);
            }
            catch(NumberFormatException e){
                t = Team2Score.getText();
            }
            finally {
                Team2Score.setText(t);
            }
        }
    }//GEN-LAST:event_Team2ScoreMouseClicked

    private void Team1Add5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team1Add5ActionPerformed
        // TODO add your handling code here:
        Integer i = Integer.parseInt(Team1Score.getText()) + 5;
        Team1Score.setText(i.toString());
    }//GEN-LAST:event_Team1Add5ActionPerformed

    private void Team1Add10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team1Add10ActionPerformed
        // TODO add your handling code here:
        Integer i = Integer.parseInt(Team1Score.getText()) + 10;
        Team1Score.setText(i.toString());
    }//GEN-LAST:event_Team1Add10ActionPerformed

    private void Team1Add15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team1Add15ActionPerformed
        // TODO add your handling code here:
        Integer i = Integer.parseInt(Team1Score.getText()) + 15;
        Team1Score.setText(i.toString());
    }//GEN-LAST:event_Team1Add15ActionPerformed

    private void Team1Add20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team1Add20ActionPerformed
        // TODO add your handling code here:
        Integer i = Integer.parseInt(Team1Score.getText()) + 20;
        Team1Score.setText(i.toString());
    }//GEN-LAST:event_Team1Add20ActionPerformed

    private void Team1Neg5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team1Neg5ActionPerformed
        // TODO add your handling code here:
        Integer i = Integer.parseInt(Team1Score.getText()) - 5;
        Team1Score.setText(i.toString());
    }//GEN-LAST:event_Team1Neg5ActionPerformed

    private void Team2Add5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team2Add5ActionPerformed
        // TODO add your handling code here:
        Integer i = Integer.parseInt(Team2Score.getText()) + 5;
        Team2Score.setText(i.toString());
    }//GEN-LAST:event_Team2Add5ActionPerformed

    private void Team2Add10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team2Add10ActionPerformed
        // TODO add your handling code here:
        Integer i = Integer.parseInt(Team2Score.getText()) + 10;
        Team2Score.setText(i.toString());
    }//GEN-LAST:event_Team2Add10ActionPerformed

    private void Team2Add15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team2Add15ActionPerformed
        // TODO add your handling code here:
        Integer i = Integer.parseInt(Team2Score.getText()) + 15;
        Team2Score.setText(i.toString());
    }//GEN-LAST:event_Team2Add15ActionPerformed

    private void Team2Add20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team2Add20ActionPerformed
        // TODO add your handling code here:
        Integer i = Integer.parseInt(Team2Score.getText()) + 20;
        Team2Score.setText(i.toString());
    }//GEN-LAST:event_Team2Add20ActionPerformed

    private void Team2Neg5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Team2Neg5ActionPerformed
        // TODO add your handling code here:
        Integer i = Integer.parseInt(Team2Score.getText()) - 5;
        Team2Score.setText(i.toString());
    }//GEN-LAST:event_Team2Neg5ActionPerformed

    private void restartTimer() {
        timer.stop();
        time = 60;
        timerLabel.setText(""+time);
        timerButton.setText("Start");
    }

    private void team1_60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team1_60ActionPerformed
        // TODO add your handling code here:
        restartTimer();
        sixtySecPtsLabel.setText(Integer.toString(0));
        bonusTotal = 0;
        resetToggles();
        timerButton.setEnabled(true);

        for(JToggleButton b : buttonList)
            b.setEnabled(true);
    }//GEN-LAST:event_team1_60ActionPerformed

    private void togglePressed(JToggleButton b)
    {
        if(!isSweep() && bonusTotal<=100) {
            if (b.isSelected())
                bonusTotal += 10;
            else
                bonusTotal -= 10;
            sweepLabel.setVisible(false);
        }
        else if(isSweep())
            sweepLabel.setVisible(true);
        else
            bonusTotal = 90;
        
        sixtySecPtsLabel.setText(Integer.toString(bonusTotal));
    }

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        // TODO add your handling code here:
        togglePressed(q1);
    }//GEN-LAST:event_q1ActionPerformed

    private boolean isSweep() {
        for (JToggleButton b : buttonList)
            if (!b.isSelected()) {
                sweepLabel.setVisible(false);
                return false;
            }
        bonusTotal = 120;
        return true;
    }

    private void resetToggles() {

        for(JToggleButton b : buttonList){
            b.setSelected(false);
            b.setEnabled(false);
        }
        sweepLabel.setVisible(false);
        //timerButton.setEnabled(false);
        time = 60;
        timerLabel.setText(""+time);
    }

    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
        // TODO add your handling code here:
        togglePressed(q2);
    }//GEN-LAST:event_q2ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        // TODO add your handling code here:
        togglePressed(q3);
    }//GEN-LAST:event_q3ActionPerformed

    private void q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4ActionPerformed
        // TODO add your handling code here:
        togglePressed(q4);
    }//GEN-LAST:event_q4ActionPerformed

    private void q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5ActionPerformed
        // TODO add your handling code here:
        togglePressed(q5);
    }//GEN-LAST:event_q5ActionPerformed

    private void q6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6ActionPerformed
        // TODO add your handling code here:
        togglePressed(q6);
    }//GEN-LAST:event_q6ActionPerformed

    private void q7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q7ActionPerformed
        // TODO add your handling code here:
        togglePressed(q7);
    }//GEN-LAST:event_q7ActionPerformed

    private void q8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q8ActionPerformed
        // TODO add your handling code here:
        togglePressed(q8);
    }//GEN-LAST:event_q8ActionPerformed

    private void team2_60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team2_60ActionPerformed
        // TODO add your handling code here:
        bonusTotal = 0;
        sixtySecPtsLabel.setText(Integer.toString(0));
        restartTimer();
        resetToggles();
        timerButton.setEnabled(true);


        for(JToggleButton b : buttonList)
            b.setEnabled(true);
    }//GEN-LAST:event_team2_60ActionPerformed

    private void SixtySecondPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixtySecondPointsActionPerformed
        if(team1_60.isSelected()){
            Team1Score.setText(Integer.toString(Integer.parseInt(Team1Score.getText())+bonusTotal));
        }
        else if (team2_60.isSelected()){
            Team2Score.setText(Integer.toString(Integer.parseInt(Team2Score.getText())+bonusTotal));
        }
        bonusTotal = 0;
        resetToggles();
        timerButton.setEnabled(false);
        sixtySecPtsLabel.setText(Integer.toString(0));
        buttonGroup.clearSelection();
    }//GEN-LAST:event_SixtySecondPointsActionPerformed

    private void timerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timerButtonActionPerformed
        // TODO add your handling code here:
        if (time == 60){
            time--;
            timer.start();
            timerLabel.setText(""+time);
            timerButton.setText("Reset");
        }
        else {
            time=60;
            timer.stop();
            timerLabel.setText(""+time);
            timerButton.setText("Start");
            //timerButton.setEnabled(false);
        }
    }//GEN-LAST:event_timerButtonActionPerformed


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SixtySecondPanel;
    private javax.swing.JButton SixtySecondPoints;
    private javax.swing.JButton Team1Add10;
    private javax.swing.JButton Team1Add15;
    private javax.swing.JButton Team1Add20;
    private javax.swing.JButton Team1Add5;
    private javax.swing.JLabel Team1Label;
    private javax.swing.JButton Team1Neg5;
    private javax.swing.JPanel Team1Panel;
    private javax.swing.JPanel Team1PointsPanel;
    private javax.swing.JLabel Team1Score;
    private javax.swing.JButton Team2Add10;
    private javax.swing.JButton Team2Add15;
    private javax.swing.JButton Team2Add20;
    private javax.swing.JButton Team2Add5;
    private javax.swing.JLabel Team2Label;
    private javax.swing.JButton Team2Neg5;
    private javax.swing.JPanel Team2Panel;
    private javax.swing.JPanel Team2PointsPanel;
    private javax.swing.JLabel Team2Score;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JToggleButton q1;
    private javax.swing.JToggleButton q10;
    private javax.swing.JToggleButton q2;
    private javax.swing.JToggleButton q3;
    private javax.swing.JToggleButton q4;
    private javax.swing.JToggleButton q5;
    private javax.swing.JToggleButton q6;
    private javax.swing.JToggleButton q7;
    private javax.swing.JToggleButton q8;
    private javax.swing.JToggleButton q9;
    private javax.swing.JLabel sixtySecPtsLabel;
    private javax.swing.JLabel sweepLabel;
    private javax.swing.JRadioButton team1_60;
    private javax.swing.JRadioButton team2_60;
    private javax.swing.JButton timerButton;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables

}
